# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aa78bf0f584f14a4f734db0bfe9437efb7a8a3477990feda78d26f0e9ba5cda89376074ab7230de280483a115af1dce35edb2d19c9d769d74b225101cc1ce0a1

test:
  secret_key_base: 0ade63ae900c047aac582aa38716dc978925fa2195a7993354d0cb58dbfbcb02660ba8be910ff108242963dcae435f92b170f7eea94e3859d7b5cdc25db31341

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
